/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\dcai\\Desktop\\studypro\\smallgao-bolg\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-01548842",
    path: "/views/essay/20190928.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01548842").then(next)
    },
  },
  {
    name: "v-425474f3",
    path: "/views/essay/20191116.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-425474f3").then(next)
    },
  },
  {
    name: "v-0e1e21ed",
    path: "/views/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e1e21ed").then(next)
    },
  },
  {
    path: "/views/index.html",
    redirect: "/views/"
  },
  {
    name: "v-70ad3afa",
    path: "/views/essay/20191130.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70ad3afa").then(next)
    },
  },
  {
    name: "v-a8f65c7a",
    path: "/views/essay/20200227.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8f65c7a").then(next)
    },
  },
  {
    name: "v-0ca1c3ee",
    path: "/views/essay/20200301.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ca1c3ee").then(next)
    },
  },
  {
    name: "v-00ac03aa",
    path: "/views/essay/20191109.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00ac03aa").then(next)
    },
  },
  {
    name: "v-82904d06",
    path: "/views/essay/20200703.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82904d06").then(next)
    },
  },
  {
    name: "v-0d49e57b",
    path: "/views/essay/20200715.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d49e57b").then(next)
    },
  },
  {
    name: "v-0ecf6c86",
    path: "/views/essay/20200813.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ecf6c86").then(next)
    },
  },
  {
    name: "v-ba4cab7a",
    path: "/views/essay/20211216.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba4cab7a").then(next)
    },
  },
  {
    name: "v-1d8345ed",
    path: "/views/essay/20220808.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d8345ed").then(next)
    },
  },
  {
    name: "v-f070eade",
    path: "/views/essay/20201012.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f070eade").then(next)
    },
  },
  {
    name: "v-eef8d5fe",
    path: "/views/essay/20201119.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eef8d5fe").then(next)
    },
  },
  {
    name: "v-b6e3a2c6",
    path: "/views/frontend/EChartsStudy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6e3a2c6").then(next)
    },
  },
  {
    name: "v-67a514f5",
    path: "/views/essay/20230605.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67a514f5").then(next)
    },
  },
  {
    name: "v-73f785ae",
    path: "/views/frontend/reco-info.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73f785ae").then(next)
    },
  },
  {
    name: "v-4bce123d",
    path: "/views/frontend/viaStart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bce123d").then(next)
    },
  },
  {
    name: "v-5e66af89",
    path: "/views/frontend/js-json.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e66af89").then(next)
    },
  },
  {
    name: "v-8bea6006",
    path: "/views/frontend/vue-demo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8bea6006").then(next)
    },
  },
  {
    name: "v-bb051ac6",
    path: "/views/frontend/vuepress-plugin-boxx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bb051ac6").then(next)
    },
  },
  {
    name: "v-13e039be",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13e039be").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-835a9522",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-835a9522").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-607e192e",
    path: "/views/frontend/TCP&UDP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-607e192e").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-1eedfa34",
    path: "/tag/随笔/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1eedfa34").then(next)
    },
    meta: {"pid":"tags","id":"随笔"}
  },
  {
    path: "/tag/随笔/index.html",
    redirect: "/tag/随笔/"
  },
  {
    name: "v-5e43a71f",
    path: "/tag/ECharts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5e43a71f").then(next)
    },
    meta: {"pid":"tags","id":"ECharts"}
  },
  {
    path: "/tag/ECharts/index.html",
    redirect: "/tag/ECharts/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dfb71430").then(next)
    },
    meta: {"pid":"tags","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-3247b8aa",
    path: "/tag/Via/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3247b8aa").then(next)
    },
    meta: {"pid":"tags","id":"Via"}
  },
  {
    path: "/tag/Via/index.html",
    redirect: "/tag/Via/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-14722046",
    path: "/tag/json/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-14722046").then(next)
    },
    meta: {"pid":"tags","id":"json"}
  },
  {
    path: "/tag/json/index.html",
    redirect: "/tag/json/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-3c2760d0",
    path: "/tag/网络协议/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3c2760d0").then(next)
    },
    meta: {"pid":"tags","id":"网络协议"}
  },
  {
    path: "/tag/网络协议/index.html",
    redirect: "/tag/网络协议/"
  },
  {
    name: "v-ab316f34",
    path: "/categories/随笔 Essay/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-ab316f34").then(next)
    },
    meta: {"pid":"categories","id":"随笔 Essay"}
  },
  {
    path: "/categories/随笔 Essay/index.html",
    redirect: "/categories/随笔 Essay/"
  },
  {
    name: "v-60e851e2",
    path: "/categories/前端 Front-end/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-60e851e2").then(next)
    },
    meta: {"pid":"categories","id":"前端 Front-end"}
  },
  {
    path: "/categories/前端 Front-end/index.html",
    redirect: "/categories/前端 Front-end/"
  },
  {
    name: "v-e09e3912",
    path: "/categories/规范 Standard/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-e09e3912").then(next)
    },
    meta: {"pid":"categories","id":"规范 Standard"}
  },
  {
    path: "/categories/规范 Standard/index.html",
    redirect: "/categories/规范 Standard/"
  },
  {
    name: "v-7c1bf909",
    path: "/tag/随笔/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c1bf909").then(next)
    },
    meta: {"pid":"tags","id":"随笔"}
  },
  {
    path: "/tag/随笔/page/2/index.html",
    redirect: "/tag/随笔/page/2/"
  },
  {
    name: "v-a7aca2d2",
    path: "/categories/随笔 Essay/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7aca2d2").then(next)
    },
    meta: {"pid":"categories","id":"随笔 Essay"}
  },
  {
    path: "/categories/随笔 Essay/page/2/index.html",
    redirect: "/categories/随笔 Essay/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]