/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "随笔": {
      "key": "随笔",
      "scope": "tags",
      "path": "/tag/随笔/",
      "pageKeys": [
        "v-01548842",
        "v-425474f3",
        "v-70ad3afa",
        "v-a8f65c7a",
        "v-0ca1c3ee",
        "v-00ac03aa",
        "v-82904d06",
        "v-0d49e57b",
        "v-0ecf6c86",
        "v-ba4cab7a",
        "v-1d8345ed",
        "v-f070eade",
        "v-eef8d5fe",
        "v-67a514f5"
      ]
    },
    "ECharts": {
      "key": "ECharts",
      "scope": "tags",
      "path": "/tag/ECharts/",
      "pageKeys": [
        "v-b6e3a2c6"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-73f785ae",
        "v-bb051ac6"
      ]
    },
    "Via": {
      "key": "Via",
      "scope": "tags",
      "path": "/tag/Via/",
      "pageKeys": [
        "v-4bce123d"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-5e66af89"
      ]
    },
    "json": {
      "key": "json",
      "scope": "tags",
      "path": "/tag/json/",
      "pageKeys": [
        "v-5e66af89"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-8bea6006"
      ]
    },
    "网络协议": {
      "key": "网络协议",
      "scope": "tags",
      "path": "/tag/网络协议/",
      "pageKeys": [
        "v-607e192e"
      ]
    }
  },
  "categories": {
    "随笔 Essay": {
      "key": "随笔 Essay",
      "scope": "categories",
      "path": "/categories/随笔 Essay/",
      "pageKeys": [
        "v-01548842",
        "v-425474f3",
        "v-70ad3afa",
        "v-a8f65c7a",
        "v-0ca1c3ee",
        "v-00ac03aa",
        "v-82904d06",
        "v-0d49e57b",
        "v-0ecf6c86",
        "v-ba4cab7a",
        "v-1d8345ed",
        "v-f070eade",
        "v-eef8d5fe",
        "v-67a514f5"
      ]
    },
    "前端 Front-end": {
      "key": "前端 Front-end",
      "scope": "categories",
      "path": "/categories/前端 Front-end/",
      "pageKeys": [
        "v-b6e3a2c6",
        "v-73f785ae",
        "v-4bce123d",
        "v-5e66af89",
        "v-8bea6006",
        "v-bb051ac6",
        "v-607e192e"
      ]
    },
    "规范 Standard": {
      "key": "规范 Standard",
      "scope": "categories",
      "path": "/categories/规范 Standard/",
      "pageKeys": [
        "v-607e192e"
      ]
    }
  },
  "timeline": {}
}